name: portfolio
description: Ganeshprasad Shenoy. I am passionate about learning new technologies with happy go lucky attitude.

version: 1.0.0+1

environment:
      sdk: ">=2.1.0 <3.0.0"

dependencies:
      flutter:
            sdk: flutter
      flip_card: ^0.4.4
      google_fonts: ^0.2.0
      url_launcher: ^5.4.1
      url_launcher_web: ^0.1.0+2
      responsive_builder: ^0.1.4
      build_runner: ^1.8.1
      build_web_compilers: ^2.10.0

      cupertino_icons: ^0.1.2

dev_dependencies:
      flutter_test:
            sdk: flutter

flutter:
      uses-material-design: true
      assets:
       - assets/
